//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanDienThoai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpecification
    {
        public int SpecID { get; set; }
        public int ProductID { get; set; }
        public int SpecCategoryID { get; set; }
        public string SpecName { get; set; }
        public string SpecValue { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SpecificationCategory SpecificationCategory { get; set; }
    }
}
